import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

test("sync generates managed Trae and Grok files with the auto-generated header", async () => {
  await execFileAsync("node", ["scripts/sync.mjs"], { cwd: root });
  const files = [
    "AGENTS.md",
    "docs/agents.md",
    "docs/trae.md",
    "docs/grok.md",
    ".trae/settings.json",
    ".grok/rules/session-start.md",
    ".grok/agents/business-orchestrator.md",
    ".grok/skills/memory-stewardship/SKILL.md",
    ".grok/commands/sync-workspace.md"
  ];
  for (const file of files) {
    const content = await fs.readFile(path.join(root, file), "utf8");
    assert.match(content, /AUTO-GENERATED by starter/);
  }

  const agents = await fs.readFile(path.join(root, "AGENTS.md"), "utf8");
  assert.match(agents, /Trae IDE and Grok Build/);
  assert.match(agents, /memory\/handoff\.md/);
});
