# -*- coding: utf-8 -*-
"""Write all full-quality user guide chapters + masters. Depends on SVGs from build_user_guide.py."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BOOK = ROOT / "book" / "user_guide"
CH = BOOK / "chapters"
AS = BOOK / "assets"
CH.mkdir(parents=True, exist_ok=True)
AS.mkdir(parents=True, exist_ok=True)

# Ensure SVGs exist
subprocess.check_call([sys.executable, str(Path(__file__).parent / "build_user_guide.py")], cwd=str(ROOT))


def R() -> str:
    return (
        "> **Residual (honesty):** Executable bar includes E1, video **recommend**, viral-hook DNA with **stubs**, "
        "and **17** special skills from REGISTRY. **Not claimed:** live Sora/Veo/Runway, full studio, all DNA "
        "`production_ready`, agent fleet true-100. See `EXECUTABLE_PRODUCT.md`.\n"
    )


def quiz(pairs: list[tuple[str, str]]) -> str:
    lines = ["## Knowledge check\n"]
    for i, (q, _) in enumerate(pairs, 1):
        lines.append(f"{i}. {q}")
    lines.append("\n<details>\n<summary>Answer key</summary>\n")
    for i, (_, a) in enumerate(pairs, 1):
        lines.append(f"{i}. {a}")
    lines.append("\n</details>\n")
    return "\n".join(lines)


def write(name: str, content: str) -> None:
    (CH / name).write_text(content.strip() + "\n", encoding="utf-8")
    print("OK", name)


def nav(prev: str | None, nxt: str | None) -> str:
    lines = ["## Navigation\n"]
    if prev:
        lines.append(f"- Previous: [`{prev}`](./{prev})")
    if nxt:
        lines.append(f"- Next: [`{nxt}`](./{nxt})")
    lines.append("- Guide home: [../user_guide.md](../user_guide.md)")
    return "\n".join(lines) + "\n"


# ========== CHAPTERS ==========

write(
    "01-01-system-overview.md",
    f"""
# 1.1 System overview

| | |
|--|--|
| **Section** | 1 — Core System Fundamentals |
| **Level** | Beginner |
| **Est. time** | 35–45 minutes |

## Learning objectives

- Explain generic-swarm-ops in one plain-language paragraph
- Name the four planes and their repo locations
- Define agent, tool, DNA, run, approval, domain pack
- State the N1 rule and the product honesty bar

## Prerequisites

- Access to the `generic-swarm-ops` repository
- No prior multi-agent experience required

## Illustration

![Four-plane system architecture](../assets/01-01-system-architecture.svg)

*Figure 1.1 — Control plane, console, business OS, and domain packs*

{R()}

## Why this system exists

Most multi-agent demos are chat transcripts: weak audit, weak control over irreversible actions, and unsafe “improve in production” habits. **generic-swarm-ops** is a **governed multi-agent business operating system**. Operators execute **workflow DNA** (structured process graphs) on a **FastAPI control plane**, with **tool allow-lists**, **human approval gates**, **audit trails**, and **sandbox evolution**, using a **Next.js ops console**.

## The four planes

| Plane | Path | Responsibility |
|-------|------|----------------|
| Ops console | `frontend/` | Human UI for runs, approvals, Domains, evolution |
| Control plane | `backend/` | Auth, DNA engine (`runtime.py`), tools, APIs |
| Business OS | `business/` | PI, evals, governance files, lessons |
| Domain packs | e.g. `business/video/` | Domain agents, DNA, corpus, special skills |

**Agent harnesses** (`.trae/`, `.grok/`) are generated by `npm run sync` for coding agents. They are **not** a second workflow runtime.

## Core vocabulary

| Term | Meaning |
|------|---------|
| Agent | Runtime role with `allowed_tools[]` |
| Tool | Adapter that performs work and records `tool_effects` |
| DNA | Versioned workflow definition (`*.dna.json`) |
| Run | One DNA execution with status/events |
| Approval | Human decision on a gated step |
| Domain pack | Versioned domain bundle under `business/<name>/` |
| Special skill | Catalogued pack integration (video: **17**) |

## Request path (mental model)

1. UI or API client calls `/api/v1/...` with credentials.  
2. Route handlers call `RuntimeServices` in `backend/app/runtime.py`.  
3. DNA steps bind agents + allow-listed tools.  
4. Tools execute; audit/effects are stored.  
5. High-risk steps pause for approvals.  
6. Terminal runs may **reflect** lessons; DNA promotion stays sandbox-gated.

## Hands-on orientation

1. Open root `README.md` and `EXECUTABLE_PRODUCT.md`.  
2. Copy the **Proven** vs **Not claimed** table into your notes.  
3. List top-level folders; label each plane.  
4. Skim `docs/architecture.md` once.

**Expected:** You can answer “what is this?” without saying only “it uses AI.”

## Real-world use cases

### Use case 1 — Compliance-minded ops lead

You automate customer onboarding but need human sign-off on billing. E1 maps cleanly: run DNA → approval gate → audit log. You refuse demos that skip gates.

### Use case 2 — Content producer

You want short-form process selection. Use Domains **recommend** for DNA identity (e.g. viral-hook). You accept media stubs as process design, not finished video.

### Use case 3 — Platform engineer

You own reliability. You treat Postgres + FastAPI as the control plane, packs as plugins, frontend as a client.

## Best practices

- Keep domain logic in packs (N1).  
- Do not hand-edit `.trae/` / `.grok/`.  
- Use `book/design_phase/` for deep architecture later, not day one.  
- State residuals when presenting to stakeholders.

## Chapter summary

- Governed multi-agent business OS with four planes  
- DNA + tools + gates + audit at the core  
- Executable bar is smaller than full studio ambition—and that is intentional  

{quiz([
    ("What is N1?", "Domain logic stays in the pack; host runs DNA/tools/gates."),
    ("Name a proven path.", "E1, recommend, or viral-hook with stubs."),
    ("Is `.grok/` the workflow engine?", "No—agent harness only."),
])}

{nav(None, "01-02-prerequisites-and-environment.md")}
""",
)

write(
    "01-02-prerequisites-and-environment.md",
    f"""
# 1.2 Prerequisites and environment

| | |
|--|--|
| **Section** | 1 — Core System Fundamentals |
| **Level** | Beginner |
| **Est. time** | 25–40 minutes |

## Learning objectives

- Verify Node 20+, Python 3.11+, pnpm, and Git
- Choose Postgres vs JSON-file learning mode
- Confirm ports and dual-terminal workflow

## Prerequisites

- Chapter 1.1
- Permission to install developer tools if missing

## Illustration

![Toolchain prerequisites](../assets/01-02-prerequisites.svg)

*Figure 1.2 — Required toolchain*

{R()}

## Required software

| Tool | Guidance |
|------|----------|
| Node.js | **20+** (npm included) |
| Python | **3.11+** |
| pnpm | Via `corepack enable` or standalone |
| Git | Recent |
| PostgreSQL 14+ | Recommended for durable/shared work |

## Verify (PowerShell)

```powershell
node -v
npm -v
python --version
git --version
corepack enable
pnpm -v
```

**Expected:** Node v20+; Python 3.11+.

## Persistence choice

| Mode | Use when | Ready signal |
|------|----------|--------------|
| Postgres | Team / production-like | `database: postgres` |
| JSON-file | Solo learning | `database: json-file` (may be degraded) |

Details: `backend/docs/postgres-runbook.md`, `DATABASE_URL` in `backend/.env`.

## Ports

- Backend API: `http://127.0.0.1:8000`
- Frontend: typically `http://127.0.0.1:3000`

## Hands-on steps

1. Run every version command; install anything missing.  
2. Write down your repo path (example `C:\\Project\\generic-swarm-ops`).  
3. Optional: create Postgres DB `generic_swarm_ops`.  
4. Ensure you can open two terminals side by side.

**Expected:** Toolchain green; persistence mode chosen.

## Real-world use cases

### Use case 1 — Solo evaluation

Use JSON-file for the first afternoon; switch to Postgres before sharing the environment.

### Use case 2 — Shared team lab

Require Postgres and document `DATABASE_URL` in a secrets manager—not in git.

### Use case 3 — Restricted corporate laptop

Use approved Node/Python builds; if Postgres is blocked, JSON-file still allows E1 learning.

## Best practices

- Record exact versions in a team wiki once the project is shared.  
- Prefer a virtualenv for Python if policy requires isolation.  
- Do not commit `.env` files with secrets.

## Chapter summary

- Toolchain: Node 20+, Python 3.11+, pnpm, Git  
- Postgres preferred; JSON-file OK for learning  
- Defaults: API :8000, UI :3000  

{quiz([
    ("Minimum Node major version?", "20+"),
    ("Is Postgres mandatory for first learning?", "No—JSON-file works for learning."),
    ("Default API port?", "8000"),
])}

{nav("01-01-system-overview.md", "01-03-install-bootstrap-first-boot.md")}
""",
)

write(
    "01-03-install-bootstrap-first-boot.md",
    f"""
# 1.3 Install, bootstrap, and first boot

| | |
|--|--|
| **Section** | 1 — Core System Fundamentals |
| **Level** | Beginner |
| **Est. time** | 45–90 minutes |

## Learning objectives

- Bootstrap the repository and run doctor
- Start the backend and interpret health/ready
- Start the frontend in **live** mode (demoMode off)
- Sign in with seed credentials

## Prerequisites

- Chapters 1.1–1.2 complete
- Repo clone on disk

## Illustration

![First boot sequence](../assets/01-03-first-boot.svg)

*Figure 1.3 — Bootstrap → backend → ready → frontend → login*

{R()}

## Step 1 — Bootstrap (repo root)

```powershell
cd C:\\Project\\generic-swarm-ops   # or your path
npm run bootstrap
npm run doctor
```

Optional harness sync:

```powershell
npm run sync
npm run sync:check
```

**Expected:** Doctor completes without blocking failures. Sync regenerates `.trae/` and `.grok/`.

## Step 2 — Backend

```powershell
cd backend
python -m pip install -e .
$env:PYTHONPATH = "."
# Optional: copy .env.example to .env and set DATABASE_URL
uvicorn app.main:app --reload --host 127.0.0.1 --port 8000
```

In a second terminal:

```powershell
Invoke-RestMethod http://127.0.0.1:8000/api/v1/health
Invoke-RestMethod http://127.0.0.1:8000/api/v1/health/live
Invoke-RestMethod http://127.0.0.1:8000/api/v1/health/ready
```

**Expected:**

| Endpoint | Expect |
|----------|--------|
| `/health` | status ok-style payload |
| `/health/live` | alive |
| `/health/ready` | `ready` or `degraded`; `dependencies.database` is `postgres` or `json-file` |

Product check script (optional):

```powershell
cd C:\\Project\\generic-swarm-ops
python scripts/business/check_executable_product.py
```

## Step 3 — Frontend (live ops profile)

> **Warning:** If `NEXT_PUBLIC_DEMO_MODE` is `true`, panels use **mocks** (fake skills, demo recommend). For real APIs, demo must be **off**. Product default is opt-in demo (`=== "true"` only).

```powershell
cd frontend
$env:NEXT_PUBLIC_DEMO_MODE = "false"
$env:NEXT_PUBLIC_API_BASE_URL = "http://127.0.0.1:8000/api/v1"
pnpm install
pnpm dev
```

Prefer a `.env.local` from `frontend/.env.example` with `NEXT_PUBLIC_DEMO_MODE=false`.

## Step 4 — Login

Open the local URL (usually `http://127.0.0.1:3000`).

| Field | Value |
|-------|--------|
| Email | `admin@example.com` |
| Password | `admin-password` |

**Expected:** You land in the authenticated app shell (dashboard / app routes).

## Troubleshooting first boot

| Symptom | Fix |
|---------|-----|
| Connection refused :8000 | Start uvicorn; check port |
| ready degraded | OK on JSON-file; set `DATABASE_URL` for Postgres |
| UI shows demo data | Force `NEXT_PUBLIC_DEMO_MODE=false` and restart Next |
| Login fails | Backend up? exact seed password? |

## Real-world use cases

### Use case 1 — Workshop setup

Script bootstrap + backend + frontend in three terminals; project health/ready on a slide.

### Use case 2 — CI smoke

Run unit/e2e tests instead of UI for automated verification (`test_e1_operator_path.py`).

### Use case 3 — Air-gapped laptop

Use JSON-file store; skip source download until network allows.

## Best practices

- Keep demoMode false on shared machines.  
- Never use seed passwords outside local labs.  
- Pin `API_BASE_URL` to the backend you actually started.

## Chapter summary

- bootstrap + doctor establish the tree  
- Backend health proves control plane  
- Live frontend + seed login opens operator path  

{quiz([
    ("Seed email?", "admin@example.com"),
    ("Why demoMode false?", "So UI calls real APIs instead of mocks."),
    ("What does ready database field show?", "postgres or json-file"),
])}

{nav("01-02-prerequisites-and-environment.md", "01-04-ops-console-navigation.md")}
""",
)

write(
    "01-04-ops-console-navigation.md",
    f"""
# 1.4 Ops console navigation

| | |
|--|--|
| **Section** | 1 — Core System Fundamentals |
| **Level** | Beginner |
| **Est. time** | 25–35 minutes |

## Learning objectives

- Navigate every primary sidebar group
- Open **Domains** without typing the URL
- Map labels to routes (`appPaths`)

## Prerequisites

- Chapter 1.3 — logged into live UI

## Illustration

![Ops console map](../assets/01-04-console-map.svg)

*Figure 1.4 — Sidebar IA and Domains content*

{R()}

## How navigation is built

The sidebar renders `NAVIGATION_GROUPS` from `frontend/src/types/navigation.ts`. Items without permission are hidden. **Domains** uses `appPaths.domains` → `/app/domains`.

If Domains is missing from that list, the page can exist but be **unreachable** from the shell—treat that as a product bug.

## Route map (operator)

| Label | Route | You use it for |
|-------|-------|----------------|
| Dashboard | `/app` | Overview |
| Agents | `/app/agents` | Agent inventory / create |
| **Domains** | `/app/domains` | Recommend DNA, special skills, pack panels |
| Tools | `/app/tools` | Tool catalog |
| Workflows | `/app/workflows` | Run DNA / definitions |
| Approvals | `/app/approvals` | Human gates |
| Knowledge | `/app/knowledge` | Retrieval UI |
| Memory | `/app/memory` | Memory scopes |
| Evaluations | `/app/evaluations` | Eval views |
| Processes | `/app/processes` | Process intelligence |
| Evolution | `/app/evolution` | Fitness archive |
| Audit Logs | `/app/audit-logs` | Audit trail |
| Settings / Users / API Keys | `/app/settings/...` | Admin |

## Domains panels (preview)

On `/app/domains` you should see:

1. **Recommend workflow** — free-text brief → ranked DNA  
2. **Special skills** — catalog from REGISTRY (17)  
3. Pack / roster context as implemented  

Copy should say this is **not** a live media studio.

## Hands-on steps

1. Click each **Main** item; note empty states (normal on sparse seed data).  
2. Open **Domains**; confirm recommend + special skills panels render.  
3. Open **Approvals** and **Audit Logs** so you know where gates land.  
4. Optional: open browser devtools Network tab and confirm API host is `:8000`.

**Expected:** Domains is one click away; you recognize empty vs error states.

## Real-world use cases

### Use case 1 — New hire day one

Shadow an operator: Dashboard → Workflows → Approvals → Audit, without backend deep-dives yet.

### Use case 2 — Support triage

Ask “what URL and role?” before debugging—permission-hidden nav is common.

### Use case 3 — Demo script

Always start Domains after E1 to show recommend without implying finished video output.

## Best practices

- Prefer sidebar over memorized URLs.  
- If a page is blank, check role permissions before filing a bug.  
- Keep demoMode false when demonstrating “real” data.

## Chapter summary

- Sidebar is permission-filtered from `NAVIGATION_GROUPS`  
- Domains is the pack operator surface  
- Know Approvals + Audit for the next section  

{quiz([
    ("What route is Domains?", "/app/domains"),
    ("What config drives the sidebar?", "NAVIGATION_GROUPS in navigation.ts"),
    ("Why might a user not see Settings?", "Missing permissions for their role"),
])}

{nav("01-03-install-bootstrap-first-boot.md", "01-05-accounts-login-and-session.md")}
""",
)

write(
    "01-05-accounts-login-and-session.md",
    f"""
# 1.5 Accounts, login, and session

| | |
|--|--|
| **Section** | 1 — Core System Fundamentals |
| **Level** | Beginner |
| **Est. time** | 20–30 minutes |

## Learning objectives

- Complete password login and understand session storage
- Distinguish live auth from demo preview
- Know seed credentials and when to retire them

## Prerequisites

- Backend + frontend running (1.3)

## Illustration

![Login and session path](../assets/01-05-auth-session.svg)

*Figure 1.5 — Login → token → app routes*

{R()}

## Seed account (local only)

| Field | Value |
|-------|--------|
| Email | `admin@example.com` |
| Password | `admin-password` |

> **Warning:** Change or disable seed credentials before any shared or production deployment.

Static bearer tokens (if documented as `admin-token`) are for **curl smoke only**. Prefer password login for the UI path.

## Login flow (live mode)

1. Open `/login` (or marketing entry that routes to login).  
2. Submit email/password.  
3. Backend `POST /api/v1/auth/login` returns `access_token` + user.  
4. Client stores token (cookie `gso_access_token` / memory) for subsequent API calls.  
5. App shell loads `/app/*` routes.

In **demoMode**, the UI may simulate submission without a real backend—fine for layout previews, useless for E1.

## Hands-on steps

1. Log out if already in (user menu).  
2. Log in with seed credentials in live mode.  
3. Confirm you can open `/app/workflows`.  
4. Optional API check:

```powershell
$body = (@{{ email = "admin@example.com"; password = "admin-password" }} | ConvertTo-Json)
$login = Invoke-RestMethod -Method POST -Uri "http://127.0.0.1:8000/api/v1/auth/login" `
  -ContentType "application/json" -Body $body
$login.access_token.Substring(0, [Math]::Min(12, $login.access_token.Length))
```

**Expected:** Token string prints; UI session works for API calls.

## Account management surfaces

| Surface | Route | Purpose |
|---------|-------|---------|
| Users | `/app/settings/users` | Admin user administration |
| API Keys | `/app/settings/api-keys` | Machine credentials |
| Organization settings | settings forms | Org-level config |

## Real-world use cases

### Use case 1 — Break-glass admin

Seed admin for local recovery only; issue named users for humans.

### Use case 2 — Automation

API keys for CI with least privilege—not the human admin password.

### Use case 3 — Demo day

Live mode + seed login for reliability; never “demoMode true” if you will show recommend results as real.

## Best practices

- Prefer named users with RBAC over shared admin.  
- Rotate tokens.  
- Capture `request_id` on auth failures when present.

## Chapter summary

- Password login issues bearer/session for live APIs  
- Seed account is lab-only  
- demoMode changes whether auth hits the backend  

{quiz([
    ("Seed password?", "admin-password"),
    ("Cookie name often used for token?", "gso_access_token"),
    ("Should static tokens be primary for UI?", "No—password login preferred."),
])}

{nav("01-04-ops-console-navigation.md", "02-01-agents-and-tools.md")}
""",
)

print("section1 complete")
