export type AppRole =
  | "owner"
  | "admin"
  | "developer"
  | "operator"
  | "reviewer"
  | "viewer"
  | "billing_manager"
  | "security_auditor";

export type Permission =
  | "agents:read"
  | "agents:create"
  | "agents:update"
  | "tools:read"
  | "tools:update"
  | "workflows:read"
  | "workflows:create"
  | "workflows:update"
  | "workflow_runs:read"
  | "workflow_runs:cancel"
  | "workflow_runs:retry"
  | "approvals:read"
  | "approvals:approve"
  | "knowledge:read"
  | "knowledge:write"
  | "memory:read"
  | "memory:write"
  | "evaluations:read"
  | "processes:read"
  | "audit:read"
  | "settings:read"
  | "settings:update"
  | "users:read"
  | "billing:read";
