export function generatedHeader() {
  return [
    "<!-- AUTO-GENERATED by starter. Do not edit directly.",
    "Source: rules/, skills/, hooks/, mcp-configs/",
    "Run: npm run sync",
    "-->"
  ].join("\n");
}

export function managedBlock(name, content) {
  return [
    `<!-- BEGIN MANAGED ${name} -->`,
    content.trimEnd(),
    `<!-- END MANAGED ${name} -->`
  ].join("\n");
}

export function formatList(items) {
  return items.map((item) => `- ${item}`).join("\n");
}
