# -*- coding: utf-8 -*-
"""Generate planning/migration/tasks.md with implement+review+score 100 per agent."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ORDER = ROOT / "planning" / "migration" / "agent_implement_order_list.md"
OUT = ROOT / "planning" / "migration" / "tasks.md"


def main() -> None:
    text = ORDER.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str]] = []
    for line in text.splitlines():
        m = re.match(r"^\|\s*(\d+)\s*\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|", line)
        if not m:
            continue
        rows.append((int(m.group(1)), m.group(2), m.group(3)))
    if len(rows) != 114:
        raise SystemExit(f"expected 114 agents, got {len(rows)}")

    L: list[str] = []
    a = L.append

    a("# Migration tasks — implement, review, score **100** per agent")
    a("")
    a("**Status:** active checklist  ")
    a("**Order source:** [`agent_implement_order_list.md`](./agent_implement_order_list.md)  ")
    a("**Prompt source:** per-agent [`video.<id>.md`](./README.md)  ")
    a("**Agent folder:** `business/video/agents/<id>/`  ")
    a("")
    a("## Goal")
    a("")
    a("For **every** of the **114** video agents, in **order seq**:")
    a("")
    a("1. **Implement** the agent materials using its migration prompt.")
    a("2. **Review** against the global scorecard.")
    a("3. **Score must be 100/100** before the agent is done.")
    a("4. **Do not start agent N+1** until agent N is **score 100** (unless blocked + documented).")
    a("")
    a("**Fleet exit:** 114/114 agents at score **100** + inventory + corpus standalone still green.")
    a("")
    a("---")
    a("")
    a("## Global scorecard (must total **100**)")
    a("")
    a("Score each agent with the same rubric. **Exit requires every dimension at full marks** (100 only).")
    a("")
    a("| Dim | Points | Full-mark criteria (all required) |")
    a("|-----|-------:|-----------------------------------|")
    a("| **S1 Self-contained SPEC** | 25 | `SPEC.md` is not refer-only; embeds roster/corpus content; no required external `va-agent-swarm/study` primary path; substantial depth (typically ≥8 KB after implement) |")
    a("| **S2 Corpus fidelity** | 20 | Relevant `business/video/corpus` (+ va if used) integrated into SPEC and/or `sources/`; core definition does not depend on missing external repo |")
    a("| **S3 Prompt execution** | 15 | Full run of `planning/migration/<agent_id>.md` including **role-specific** arXiv / X / YouTube capability research integrated into SPEC |")
    a("| **S4 Runtime binding** | 15 | `agent_spec.json` ALC-complete (`requires_alc`, memory scopes include agent, `alc_version`, reflect); design-time vs runtime tools separated; no illegal allow-list expansion |")
    a("| **S5 Reachability** | 10 | In ROSTER/MAP/standby; pack_id consistent; DNA or standby reachability noted |")
    a("| **S6 Review quality** | 15 | S6 checklist all ✓; no open P0 defects; reviewer confirms total **100** |")
    a("| **Total** | **100** | Agent complete **only if 100** |")
    a("")
    a("### Score rules")
    a("")
    a("- Progression is **binary**: **100 = pass**, **&lt;100 = fail → rework → re-review**.")
    a("- Incomplete dimension ⇒ total is **not** 100.")
    a("- After rework, re-score all dimensions; only then mark `done`.")
    a("")
    a("### S6 review checklist (all must be ✓ for 15 points)")
    a("")
    a("- [ ] Identity: pack_id, va_id, category correct")
    a("- [ ] Responsibility / tools / critique / architecture detailed")
    a("- [ ] Common structure (or equal depth) present")
    a("- [ ] Capability research applied (arXiv + X + YouTube themes from **this** agent’s prompt)")
    a("- [ ] N1: video logic stays in pack; no second control plane")
    a("- [ ] No auto-promote / sandbox bypass as default runtime behavior")
    a("- [ ] `sources/` present when deep docs used, **or** SPEC embeds full needed text")
    a("- [ ] Prompt file id matches agent id and folder path")
    a("")
    a("---")
    a("")
    a("## Global gates")
    a("")
    a("### G0 — Pre-flight (once)")
    a("")
    a("- [ ] `python scripts/business/inventory_check.py` → `INVENTORY PASS count=114 n3=complete`")
    a("- [ ] `python scripts/business/check_video_corpus_standalone.py` → `STANDALONE PASS`")
    a("- [ ] `business/video/corpus/MANIFEST.json` present")
    a("- [ ] 114 prompts under `planning/migration/video.*.md`")
    a("")
    a("### G1 — Fleet complete (only when all agents = 100)")
    a("")
    a("- [ ] Master table: 114 rows `done` with score **100**")
    a("- [ ] Inventory still PASS")
    a("- [ ] Standalone still PASS")
    a("- [ ] `pytest backend/app/tests/unit/test_video_corpus_standalone.py -q` green")
    a("- [ ] `memory/handoff.md` notes fleet 100 completion")
    a("")
    a("---")
    a("")
    a("## Per-agent workflow (every seq)")
    a("")
    a("1. **Implement** — execute `planning/migration/<agent_id>.md`; update agent folder.")
    a("2. **Self-check** — S1–S5 full marks.")
    a("3. **Review** — S6 checklist all ✓ (critic / second pass).")
    a("4. **Score** — must be **100**; else rework.")
    a("5. Mark master row + detailed block complete.")
    a("6. Only then advance to next order seq.")
    a("")
    a("---")
    a("")
    a("## Master task table (114)")
    a("")
    a("| order seq | agent id | implement prompt | agent folder | implement | review | score | status |")
    a("|----------:|----------|------------------|--------------|:---------:|:------:|------:|--------|")
    for seq, aid, folder in rows:
        a(
            f"| {seq} | `{aid}` | [`{aid}.md`](./{aid}.md) | `{folder}` | [ ] | [ ] | 100 | todo |"
        )
    a("")
    a("**Status:** `todo` · `in_progress` · `rework` · `done`  ")
    a("**`done` only if:** implement ✓, review ✓, score column **100**.")
    a("")
    a("---")
    a("")
    a("## Detailed tasks per agent (implement + review + score 100)")
    a("")

    for seq, aid, folder in rows:
        a(f"### T-{seq:03d} — `{aid}` — **must score 100**")
        a("")
        a(f"| Field | Value |")
        a(f"|-------|-------|")
        a(f"| Order | {seq} / 114 |")
        a(f"| Prompt | [`planning/migration/{aid}.md`](./{aid}.md) |")
        a(f"| Folder | `{folder}` |")
        a("")
        a("#### Implement")
        a("")
        a(f"- [ ] Execute full prompt [`{aid}.md`](./{aid}.md) (corpus + va; un-summarized)")
        a(f"- [ ] Update `{folder}/SPEC.md` to self-contained definition (no refer-only stubs)")
        a(f"- [ ] Confirm/update `{folder}/agent_spec.json` ALC + tools policy (design vs runtime)")
        a(f"- [ ] Populate `{folder}/sources/` when deep docs apply (or fully embed in SPEC)")
        a(f"- [ ] Integrate **this agent’s** capability research (arXiv / X / YouTube per prompt — not a copy of another agent)")
        a("")
        a("#### Review")
        a("")
        a("- [ ] S6 checklist all items ✓")
        a("- [ ] Critic pass: no P0 gaps vs corpus for this role")
        a("- [ ] N1/N3 constraints respected")
        a("")
        a("#### Scorecard (earned must equal max for each row)")
        a("")
        a("| Dim | Max | Earned |")
        a("|-----|----:|-------:|")
        a("| S1 Self-contained SPEC | 25 |  |")
        a("| S2 Corpus fidelity | 20 |  |")
        a("| S3 Prompt execution | 15 |  |")
        a("| S4 Runtime binding | 15 |  |")
        a("| S5 Reachability | 10 |  |")
        a("| S6 Review quality | 15 |  |")
        a("| **Total** | **100** |  |")
        a("")
        a("- [ ] **Final score = 100** (required to close T-%03d)" % seq)
        a("- [ ] Master table status → `done`")
        a("")
        a("---")
        a("")

    a("## Progress log")
    a("")
    a("| Date | seq range | count at 100 | notes |")
    a("|------|-----------|-------------:|-------|")
    a("| 2026-07-13 | — | 0 / 114 | tasks.md created: implement + review + score 100 per agent |")
    a("")
    a("## Related")
    a("")
    a("- [`agent_implement_order_list.md`](./agent_implement_order_list.md)")
    a("- [`README.md`](./README.md) — prompt index")
    a("- [`../../migration_plan.md`](../../migration_plan.md)")
    a("- `python scripts/business/inventory_check.py`")
    a("- `python scripts/business/check_video_corpus_standalone.py`")
    a("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT} agents={len(rows)} lines={len(L)}")


if __name__ == "__main__":
    main()
